In [2]:
import tensorflow as tf
import numpy as np

print(tf.__version__)
print(tf.executing_eagerly())

2.4.0
True


# 创建张量

tf.constant(value,dtype=,shape)函数

In [3]:
a=tf.constant([[1,2],[3,4]])#参数为python列表
print(a)
print(type(a))
print("------------------------------------------------------------------")

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
------------------------------------------------------------------


In [4]:
#转化为numpy数组
# .numpy()函数  ps:有括号
print(a)
print("------------------------------------------------------------------")
print(a.numpy())
print("------------------------------------------------------------------")
print(type(a))

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
------------------------------------------------------------------
[[1 2]
 [3 4]]
------------------------------------------------------------------
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [5]:
tf.constant(1.)#参数为数字

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [6]:
tf.constant(1,dtype=tf.float64)

<tf.Tensor: shape=(), dtype=float64, numpy=1.0>

In [7]:
a=tf.constant(np.array([[1,2],[3,4]]))#参数为numpy数组
print(a)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [8]:
#tf.cast(x,dype=)改变张量中元素的数据类型
#.dtype   ps:无括号
b=tf.cast(a,dtype=tf.float32)
print(b)
print(b.dtype)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
<dtype: 'float32'>


In [9]:
tf.constant(True) #参数为bool型

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [10]:
tf.constant("hello")#参数为字符串

<tf.Tensor: shape=(), dtype=string, numpy=b'hello'>

tf.convert_to_tensor(( 数组/列表/数字/布尔型/字符串))函数

In [11]:
na=np.arange(12).reshape(3,4)
print(na)
print(type(na))
ta=tf.convert_to_tensor(na)
print(ta)
print(type(ta))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
<class 'numpy.ndarray'>
tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]], shape=(3, 4), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [12]:
#tf.is_tensor()函数
#isinstance()函数
tf.is_tensor(ta)

True

In [13]:
isinstance(ta,tf.Tensor)

True

In [14]:
isinstance(na,np.ndarray)

True

In [15]:
#创建全0张量
#tf.ones()
#tf.zeros()
tf.ones(shape=(1,6))

<tf.Tensor: shape=(1, 6), dtype=float32, numpy=array([[1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [16]:
tf.ones([2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [17]:
#创建元素都相同的张量
#tf.fill(dims,value)
#tf.constant(value,shape=)
tf.fill([2,3],9)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[9, 9, 9],
       [9, 9, 9]])>

In [18]:
tf.constant(9,shape=[2,3])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[9, 9, 9],
       [9, 9, 9]])>

In [19]:
#创建随机数张量
#tf.random.normal(shape,mean,stddev,dtype)
tf.random.normal([2,2])#创建一个2*2张量，其元素服从正态分布

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.0920311 , -1.4152894 ],
       [ 0.06331311,  0.49964336]], dtype=float32)>

In [20]:
tf.random.normal([3,3,3],mean=0.0,stddev=2.0)

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[ 3.0067847 ,  0.25780573,  2.6877978 ],
        [-0.5884671 ,  2.151046  ,  0.7626739 ],
        [ 0.48217747, -1.0440388 ,  0.20259286]],

       [[-2.8949318 , -2.712787  ,  2.9352145 ],
        [ 2.402437  ,  3.0845077 ,  1.2208306 ],
        [ 1.8624781 , -2.8252234 ,  0.28949013]],

       [[ 0.8800881 , -2.7726507 , -1.7129673 ],
        [ 2.668379  , -3.3187804 ,  0.66562843],
        [-1.0769514 ,  1.0185257 , -2.212408  ]]], dtype=float32)>

In [21]:
#创建随机数张量——截断正态分布
#tf.random.truncated_normal(shape,mean,stddev,dtype)
tf.random.truncated_normal([3,3,3],mean=0.0,stddev=2.0)

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[-0.5529367 ,  0.8999614 ,  2.352978  ],
        [ 1.2010862 ,  2.0524573 ,  2.026579  ],
        [ 1.6000125 ,  1.6946471 ,  2.1563976 ]],

       [[-2.0597136 , -0.5352263 , -1.1939663 ],
        [-1.4466714 , -0.4758002 , -1.2500982 ],
        [-2.059885  , -0.8822256 ,  0.9678097 ]],

       [[-0.31617126, -0.3791081 , -1.0645643 ],
        [ 0.18807675,  0.42843884,  2.270852  ],
        [-0.6842056 ,  2.4956295 ,  1.0376512 ]]], dtype=float32)>

In [22]:
#设置随机种子
#tf.random.set_seed()
tf.random.set_seed(8)
tf.random.normal([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.2074401, -0.7452462],
       [ 0.6908678, -0.7635988]], dtype=float32)>

In [23]:
#创建均匀分布张量
#tf.random.uniform(shape,minval,maxval,dtype) 
tf.random.uniform([3,3],0,10,dtype=tf.int32)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[6, 8, 3],
       [9, 5, 1],
       [8, 6, 1]])>

In [24]:
#随机打乱一维
#tf.random.shuffle()
x=tf.constant([[1,2],[3,4],[5,6]])
tf.random.shuffle(x)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [5, 6],
       [3, 4]])>

In [25]:
#创建序列
#tf.range(start,limit,delta,dtypr)
tf.range(10)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [26]:
tf.range(10,delta=2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 2, 4, 6, 8])>

In [27]:
tf.range(1,10,delta=2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>

# 维度变换

In [28]:
#改变张量的形状
#tf.reshape(tensor,shape)
a=tf.range(24)
b=tf.reshape(a,[2,3,4])
b

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])>

In [29]:
tf.constant(np.arange(24).reshape(2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])>

In [30]:
#增加和删除维度 
#增加维度和删除维度，只是改变了张量的视图，不会改变张量的存储
#tf.expand_dims(input,axis)
#tf.squeeze(input,axis)
t=tf.constant([1,2])
print(t.shape)  #ps:无括号
print(t)

(2,)
tf.Tensor([1 2], shape=(2,), dtype=int32)


In [31]:
t1=tf.expand_dims(t,1)
print(t1.shape)
print(t1)

(2, 1)
tf.Tensor(
[[1]
 [2]], shape=(2, 1), dtype=int32)


In [32]:
t2=tf.expand_dims(t,0)
print(t2.shape)
print(t2)

(1, 2)
tf.Tensor([[1 2]], shape=(1, 2), dtype=int32)


In [33]:
t3=tf.expand_dims(t,-1)
print(t3.shape)
print(t3)

(2, 1)
tf.Tensor(
[[1]
 [2]], shape=(2, 1), dtype=int32)


In [34]:
#交换维度
#交换维度，不仅改变了张量的视图， 同时也改变了张量的存储顺序
#tf.transpose(a,perm)
x=tf.constant([[1,2,3],[4,5,6]])
print(x)
print("-------------------------------")
y=tf.transpose(x)
print(y)
print("-------------------------------")
z=tf.transpose(x,perm=[1,0])
print(z)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
-------------------------------
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)
-------------------------------
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


In [35]:
#拼接和分割
#tf.concat(tensors,axis)
#tf.split(value, num_or_size_splits, axis=0)
t1=[[1,2,3],[4,5,6]]
t2=[[7,8,9],[10,11,12]]
tf.concat([t1,t2],0)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])>

In [36]:
tf.concat([t1,t2],1)

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])>

In [37]:
x=tf.range(24)
x=tf.reshape(x,[4,6])
x

<tf.Tensor: shape=(4, 6), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])>

In [38]:
tf.split(x,2,0)

[<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
 array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])>,
 <tf.Tensor: shape=(2, 6), dtype=int32, numpy=
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])>]

In [39]:
tf.split(x,[1,2,1],0)

[<tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[0, 1, 2, 3, 4, 5]])>,
 <tf.Tensor: shape=(2, 6), dtype=int32, numpy=
 array([[ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]])>,
 <tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[18, 19, 20, 21, 22, 23]])>]

In [40]:
tf.split(x,[1,2,3],1)

[<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
 array([[ 0],
        [ 6],
        [12],
        [18]])>,
 <tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20]])>,
 <tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]])>]

In [41]:
#堆叠和分解
#tf.stack(values,axis)
#tf.unstack(values,axis)
#分解后得到的每个张量,和原来的张量相比，维数都少了一维
x=tf.constant([1,2,3])
y=tf.constant([4,5,6])
tf.stack((x,y),0)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [42]:
tf.stack((x,y),1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]])>

In [43]:
c=tf.constant([[1,2,3],[4,5,6]])
c

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [44]:
tf.unstack(c,axis=0)

[<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 5, 6])>]

In [45]:
tf.unstack(c,axis=1)

[<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 4])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 5])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 6])>]

# 部分采样

In [ ]:
#索引和切片
#minist[0][1][2]取第1张图片中的第2行的第3列
#一维数据切片a[::]
#二维数据切片[:,:]  ps:用逗号隔开且:可以用::
#三维数据切片[:,:,:]

In [50]:
#数据提取：根据索引，抽取出没有规律的、特定的数据
#tf.gather(params,indices)
a=tf.range(20)
tf.gather(a,[0,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 2, 3])>

In [52]:
b=tf.reshape(a,[4,5])
b

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])>

In [55]:
tf.gather(b,axis=0,indices=[0,2,3])

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])>

In [56]:
tf.gather(b,axis=1,indices=[0,2,3])

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 0,  2,  3],
       [ 5,  7,  8],
       [10, 12, 13],
       [15, 17, 18]])>

In [58]:
#同时采样多个点
#gather_nd()函数
tf.gather_nd(b,[[0,1],[1,1],[2,3]])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 1,  6, 13])>

# 张量运算

In [64]:
#基本运算
#add(x,y)  subtract(x,y)  multiply(x,y)  divide(x,y)  math.mod(x,y) 
#pow square(x)  sqrt(x)  exp(x)  math.log(x) 
#其他运算
#sign(x)  abs(x)  negative(x)  reciprocal(x) logical_not(x)  ceil(x)  floor(x)
#rint(x)  round(x)  maximum(x)  minimun(x) 
#三角函数
#运算符
a=tf.constant([1,2])
b=tf.constant([3,4])
a*b

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 8])>

In [68]:
#广播机制

In [78]:
#向量乘法
#@=tf.matmul()
#a=tf.range(6)
#a=tf.reshape(a,[2,3])
a=tf.constant(np.arange(6),shape=(2,3))
b=tf.range(6)
b=tf.reshape(b,[3,2])
a@b 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 13],
       [28, 40]])>

In [82]:
#数据统计
#tf.reduce_sum(input_tensor,axis)
#tf.reduce_mean(input_tensor,axis)
#tf.reduce_max(input_tensor,axis)
#tf.reduce_min(input_tensor,axis)
#tf.argmax(), tf.argmin()求最值索引
a=tf.constant([[1,5,3],[4,2,6]])
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 5, 3],
       [4, 2, 6]])>

In [86]:
tf.argmax(a,0)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 0, 1], dtype=int64)>

# 使用GPU

In [9]:
gpus=tf.config.experimental.list_physical_devices(device_type="GPU")
cpus=tf.config.experimental.list_physical_devices(device_type="GPU")
print(gpus)
print(cpus)

[]
[]


In [10]:
tf.test.is_gpu_available()

False

In [8]:
tf.config.list_physical_devices('GPU')

[]